name: cyber_anom
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - joblib=1.4.2
  - pyyaml=6.0.2
  - dvc=3.50.2
  - fastapi=0.115.0
  - streamlit=1.37.1
  - pip:
      - mlflow==2.14.2
      - evidently==0.4.27
      - rich==13.7.1
      - python-dotenv==1.0.1
      - torch
      - torchvision
      - torchaudio
